### ISSUE TITLE
seo.query_google_search_console cant read JSON Client Secret file

### ISSUE THREAD

**Issue by hapesurya** [practical-data-science/ecommercetools#22]
I already generate JSON Client Secret from Google API then I run Google Search Console command

df = seo.query_google_search_console(key, site_url, payload)

Then Terminal respond

Error:  Service account info was not in the expected format, missing fields token_uri, client_email.

**Comment by flyandlure** [comment]
Sounds like your client secret file isn't in the expected format. Please can you follow the steps in this guide: https://practicaldatascience.co.uk/data-engineering/how-to-create-a-google-service-account-client-secrets-json-key

Should work then.
