### ISSUE TITLE
Error: Too many requests. Google has temporarily blocked you. Try again later.

### ISSUE THREAD

**Issue by n200universe** [practical-data-science/ecommercetools#26]
I have got this issue when I test the app in my browser:
_Error: Too many requests. Google has temporarily blocked you. Try again later._
**_It must be because of Google server. But I want to ask how can I use it legally or somehow purchase this for commercial purpose?_**
Thanks!

**Comment by flyandlure** [comment]
Sorry I missed this. This is an anti-bot measure by Google. One commonly used way to overcome this is to use rotating proxies or paid APIs which perform the same task.
